# Generated by Django 4.1.3 on 2022-11-12 03:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2022, 11, 12, 3, 23, 13, 891101), null=True),
        ),
    ]
