# Generated by Django 4.1.4 on 2022-12-31 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile_number', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
