# Generated by Django 4.1.4 on 2023-01-09 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0002_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='case',
            name='rating',
            field=models.CharField(default='0', max_length=50),
        ),
    ]
