# Generated by Django 4.1.3 on 2022-11-13 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0002_alter_case_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='date',
            field=models.CharField(max_length=50),
        ),
    ]
