# Generated by Django 4.1.4 on 2022-12-22 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0002_customuser_latitude_customuser_longitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Udid_With_Num',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('udid', models.CharField(default='None', max_length=500)),
                ('unum', models.CharField(default='None', max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='latitude',
            field=models.CharField(default='0', max_length=100),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='longitude',
            field=models.CharField(default='0', max_length=100),
        ),
    ]
