# Generated by Django 4.1.4 on 2022-12-22 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0003_udid_with_num_alter_customuser_latitude_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Udid_With_Num',
            new_name='Udid_Num',
        ),
    ]
