# Generated by Django 4.1.4 on 2022-12-25 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ah', '0004_rename_udid_with_num_udid_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='worker_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='case_worker_id', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='complaint',
            name='case_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_id', to='ah.case'),
        ),
        migrations.AlterField(
            model_name='udid_num',
            name='udid',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
